//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17367
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Reflection.Adds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wdcml.Utilities.System.Reflection.Adds.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays inside other arrays in custom attributes is not supported..
        /// </summary>
        internal static string ArrayInsideArrayInAttributeNotSupported {
            get {
                return ResourceManager.GetString("ArrayInsideArrayInAttributeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly reference token expected..
        /// </summary>
        internal static string AssemblyRefTokenExpected {
            get {
                return ResourceManager.GetString("AssemblyRefTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type universe has not selected an assembly as the system assembly..
        /// </summary>
        internal static string CannotDetermineSystemAssembly {
            get {
                return ResourceManager.GetString("CannotDetermineSystemAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type {0} in module {1}..
        /// </summary>
        internal static string CannotFindTypeInModule {
            get {
                return ResourceManager.GetString("CannotFindTypeInModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve module reference on a single net module..
        /// </summary>
        internal static string CannotResolveModuleRefOnNetModule {
            get {
                return ResourceManager.GetString("CannotResolveModuleRefOnNetModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve RVA..
        /// </summary>
        internal static string CannotResolveRVA {
            get {
                return ResourceManager.GetString("CannotResolveRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case insensitive type lookup is not implemented..
        /// </summary>
        internal static string CaseInsensitiveTypeLookupNotImplemented {
            get {
                return ResourceManager.GetString("CaseInsensitiveTypeLookupNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is corrupt. Attempting to read an out of range RVA..
        /// </summary>
        internal static string CorruptImage {
            get {
                return ResourceManager.GetString("CorruptImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without an assembly qualified name, a default token resolver is required..
        /// </summary>
        internal static string DefaultTokenResolverRequired {
            get {
                return ResourceManager.GetString("DefaultTokenResolverRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer type has different token resolver..
        /// </summary>
        internal static string DifferentTokenResolverForOuterType {
            get {
                return ResourceManager.GetString("DifferentTokenResolverForOuterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence missing character after the backslash..
        /// </summary>
        internal static string EscapeSequenceMissingCharacter {
            get {
                return ResourceManager.GetString("EscapeSequenceMissingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected positive number of generic parameters. .
        /// </summary>
        internal static string ExpectedPositiveNumberOfGenericParameters {
            get {
                return ResourceManager.GetString("ExpectedPositiveNumberOfGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected property or field ID..
        /// </summary>
        internal static string ExpectedPropertyOrFieldId {
            get {
                return ResourceManager.GetString("ExpectedPropertyOrFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} token expected..
        /// </summary>
        internal static string ExpectedTokenType {
            get {
                return ResourceManager.GetString("ExpectedTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-manifest module contains assembly manifest or module is corrupted..
        /// </summary>
        internal static string ExtraAssemblyManifest {
            get {
                return ResourceManager.GetString("ExtraAssemblyManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra characters after type name..
        /// </summary>
        internal static string ExtraCharactersAfterTypeName {
            get {
                return ResourceManager.GetString("ExtraCharactersAfterTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information left after last parameter is processed..
        /// </summary>
        internal static string ExtraInformationAfterLastParameter {
            get {
                return ResourceManager.GetString("ExtraInformationAfterLastParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly qualified name requires a host..
        /// </summary>
        internal static string HostSpecifierMissing {
            get {
                return ResourceManager.GetString("HostSpecifierMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id token type expected..
        /// </summary>
        internal static string IdTokenTypeExpected {
            get {
                return ResourceManager.GetString("IdTokenTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal element type {0}..
        /// </summary>
        internal static string IllegalElementType {
            get {
                return ResourceManager.GetString("IllegalElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal layout mask..
        /// </summary>
        internal static string IllegalLayoutMask {
            get {
                return ResourceManager.GetString("IllegalLayoutMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect core element type value..
        /// </summary>
        internal static string IncorrectElementTypeValue {
            get {
                return ResourceManager.GetString("IncorrectElementTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom attribute format..
        /// </summary>
        internal static string InvalidCustomAttributeFormat {
            get {
                return ResourceManager.GetString("InvalidCustomAttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom attribute blob. Enum parameters must have full type name specified..
        /// </summary>
        internal static string InvalidCustomAttributeFormatForEnum {
            get {
                return ResourceManager.GetString("InvalidCustomAttributeFormatForEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid core element type in custom attribute blob..
        /// </summary>
        internal static string InvalidElementTypeInAttribute {
            get {
                return ResourceManager.GetString("InvalidElementTypeInAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        internal static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metadata..
        /// </summary>
        internal static string InvalidMetadata {
            get {
                return ResourceManager.GetString("InvalidMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metadata signature..
        /// </summary>
        internal static string InvalidMetadataSignature {
            get {
                return ResourceManager.GetString("InvalidMetadataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metadata token {0}..
        /// </summary>
        internal static string InvalidMetadataToken {
            get {
                return ResourceManager.GetString("InvalidMetadataToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of public key token must be even..
        /// </summary>
        internal static string InvalidPublicKeyTokenLength {
            get {
                return ResourceManager.GetString("InvalidPublicKeyTokenLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jagged array in custom attributes is not supported..
        /// </summary>
        internal static string JaggedArrayInAttributeNotSupported {
            get {
                return ResourceManager.GetString("JaggedArrayInAttributeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest module must be provided..
        /// </summary>
        internal static string ManifestModuleMustBeProvided {
            get {
                return ResourceManager.GetString("ManifestModuleMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is using unsupported binding flags {1}.
        /// </summary>
        internal static string MethodIsUsingUnsupportedBindingFlags {
            get {
                return ResourceManager.GetString("MethodIsUsingUnsupportedBindingFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method token expected..
        /// </summary>
        internal static string MethodTokenExpected {
            get {
                return ResourceManager.GetString("MethodTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest module does not contain assembly manifest or module is corrupted..
        /// </summary>
        internal static string NoAssemblyManifest {
            get {
                return ResourceManager.GetString("NoAssemblyManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be be applied to RVA fields with auto-layout..
        /// </summary>
        internal static string OperationInvalidOnAutoLayoutFields {
            get {
                return ResourceManager.GetString("OperationInvalidOnAutoLayoutFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is valid on an array type only..
        /// </summary>
        internal static string OperationValidOnArrayTypeOnly {
            get {
                return ResourceManager.GetString("OperationValidOnArrayTypeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is valid on Enum types only..
        /// </summary>
        internal static string OperationValidOnEnumOnly {
            get {
                return ResourceManager.GetString("OperationValidOnEnumOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can be applied to literal fields only..
        /// </summary>
        internal static string OperationValidOnLiteralFieldsOnly {
            get {
                return ResourceManager.GetString("OperationValidOnLiteralFieldsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is valid on RVA fields only..
        /// </summary>
        internal static string OperationValidOnRVAFieldsOnly {
            get {
                return ResourceManager.GetString("OperationValidOnRVAFieldsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved assembly must be within the same universe..
        /// </summary>
        internal static string ResolvedAssemblyMustBeWithinSameUniverse {
            get {
                return ResourceManager.GetString("ResolvedAssemblyMustBeWithinSameUniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver must resolve to a valid assembly..
        /// </summary>
        internal static string ResolverMustResolveToValidAssembly {
            get {
                return ResourceManager.GetString("ResolverMustResolveToValidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver must resolve module reference to a valid module..
        /// </summary>
        internal static string ResolverMustResolveToValidModule {
            get {
                return ResourceManager.GetString("ResolverMustResolveToValidModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver must set assembly property to this assembly..
        /// </summary>
        internal static string ResolverMustSetAssemblyProperty {
            get {
                return ResourceManager.GetString("ResolverMustSetAssemblyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This metadata importer doesn&apos;t have a base address to resolve RVA address against..
        /// </summary>
        internal static string RVAUnsupported {
            get {
                return ResourceManager.GetString("RVAUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument cannot be resolved..
        /// </summary>
        internal static string TypeArgumentCannotBeResolved {
            get {
                return ResourceManager.GetString("TypeArgumentCannotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type token expected..
        /// </summary>
        internal static string TypeTokenExpected {
            get {
                return ResourceManager.GetString("TypeTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character found while parsing..
        /// </summary>
        internal static string UnexpectedCharacterFound {
            get {
                return ResourceManager.GetString("UnexpectedCharacterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input..
        /// </summary>
        internal static string UnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("UnexpectedEndOfInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type universe cannot resolve assembly: {0}..
        /// </summary>
        internal static string UniverseCannotResolveAssembly {
            get {
                return ResourceManager.GetString("UniverseCannotResolveAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized assembly attribute: {0}..
        /// </summary>
        internal static string UnrecognizedAssemblyAttribute {
            get {
                return ResourceManager.GetString("UnrecognizedAssemblyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported exception flags {0}..
        /// </summary>
        internal static string UnsupportedExceptionFlags {
            get {
                return ResourceManager.GetString("UnsupportedExceptionFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image type..
        /// </summary>
        internal static string UnsupportedImageType {
            get {
                return ResourceManager.GetString("UnsupportedImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type argument in custom attribute signature..
        /// </summary>
        internal static string UnsupportedTypeInAttributeSignature {
            get {
                return ResourceManager.GetString("UnsupportedTypeInAttributeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method may only be called on a Type for which Type.IsGenericParameter is true..
        /// </summary>
        internal static string ValidOnGenericParameterTypeOnly {
            get {
                return ResourceManager.GetString("ValidOnGenericParameterTypeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures with variable number of arguments are not implemented..
        /// </summary>
        internal static string VarargSignaturesNotImplemented {
            get {
                return ResourceManager.GetString("VarargSignaturesNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version already defined..
        /// </summary>
        internal static string VersionAlreadyDefined {
            get {
                return ResourceManager.GetString("VersionAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows runtime type {0} cannot be found.
        /// </summary>
        internal static string WindowsRuntimeTypeNotFound {
            get {
                return ResourceManager.GetString("WindowsRuntimeTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of generic arguments..
        /// </summary>
        internal static string WrongNumberOfGenericArguments {
            get {
                return ResourceManager.GetString("WrongNumberOfGenericArguments", resourceCulture);
            }
        }
    }
}
